-- AlterTable
ALTER TABLE `PullRequest` ADD COLUMN     `create_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ALTER COLUMN `userId` DROP DEFAULT;

-- AlterTable
ALTER TABLE `Repository` ADD COLUMN     `create_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
